import { useEffect } from "react";
import MapCarte from "../components/MapCarte";

export default function HomePage() {
  const mySavedCharacters = localStorage.getItem("myTabCharacters");
  const myCharacters = mySavedCharacters ? JSON.parse(mySavedCharacters) : [];
  const tableauPersons: TypeTabsPerson[] = [
    {
      id:1,
      image: "chevalier_feu.jpg",
      name: "CHEVALIER_DE_FEU",
      health: 400,
      power: 690,
      magic: 295,
    },
    { id:2,
      image: "chevalier.jpg",
      name: "CHEVALIER_FEROCE",
      health: 400,
      power: 690,
      magic: 295,
    },
    { id:3,
      image: "dragon_epee.jpg",
      name: "DRAGON_EPEISTE",
      health: 750,
      power: 30,
      magic: 999,
    },
    { id:3,
      image: "dragon.jpg",
      name: "BEBE DRAGON",
      health: 750,
      power: 30,
      magic: 999,
    },
    { id:4,
      image: "elfe.jpg",
      name: "ELFE",
      health: 400,
      power: 690,
      magic: 295,
    },
    { id:5,
      image: "heros.jpg",
      name: "HERO_EPEISTE",
      health: 400,
      power: 690,
      magic: 295,
    },
    { id:6,
      image: "magicien_glace.jpg",
      name: "MAGICIEN_DE_GLACE",
      health: 750,
      power: 30,
      magic: 999,
    },
    { id:7,
      image: "magicienne.jpg",
      name: "MAGIENNE",
      health: 400,
      power: 690,
      magic: 295,
    },
    { id:8,
      image: "nobody.png",
      name: "NOBODY",
      health: 400,
      power: 690,
      magic: 295,
    },
    { id:9,
      image: "orc.jpg",
      name: "ORC_GUERRIER",
      health: 750,
      power: 30,
      magic: 999,
    },
    { id:10,
      image: "sorcier.jpg",
      name: "SORCIER",
      health: 400,
      power: 690,
      magic: 295,
    },
    { id:11,
      image: "sorciere_feu.jpg",
      name: "SORCIERE",
      health: 400,
      power: 690,
      magic: 295,
    },
  ];
  
  const myLocalCharacters: TypeTabsPerson[] = [...myCharacters];
  useEffect(() => {
    localStorage.setItem("myTabCharacters", JSON.stringify(tableauPersons));
  }, [tableauPersons]);

  return <MapCarte myLocalCharacters={myLocalCharacters} />;
}
